Insert into "Countys" ("Id", "Name", "Initials") values (12, 'Acre', 'AC');
Insert into "Countys" ("Id", "Name", "Initials") values (27, 'Alagoas', 'AL');
Insert into "Countys" ("Id", "Name", "Initials") values (16, 'Amapá', 'AP');
Insert into "Countys" ("Id", "Name", "Initials") values (13, 'Amazonas', 'AM');
Insert into "Countys" ("Id", "Name", "Initials") values (29, 'Bahia', 'BA');
Insert into "Countys" ("Id", "Name", "Initials") values (23, 'Ceará', 'CE');
Insert into "Countys" ("Id", "Name", "Initials") values (53, 'Distrito Federal', 'DF');
Insert into "Countys" ("Id", "Name", "Initials") values (32, 'Espírito Santo', 'ES');
Insert into "Countys" ("Id", "Name", "Initials") values (52, 'Goiás', 'GO');
Insert into "Countys" ("Id", "Name", "Initials") values (21, 'Maranhão', 'MA');
Insert into "Countys" ("Id", "Name", "Initials") values (51, 'Mato Grosso', 'MT');
Insert into "Countys" ("Id", "Name", "Initials") values (50, 'Mato Grosso do Sul', 'MS');
Insert into "Countys" ("Id", "Name", "Initials") values (31, 'Minas Gerais', 'MG');
Insert into "Countys" ("Id", "Name", "Initials") values (15, 'Pará', 'PA');
Insert into "Countys" ("Id", "Name", "Initials") values (25, 'Paraíba', 'PB');
Insert into "Countys" ("Id", "Name", "Initials") values (41, 'Paraná', 'PR');
Insert into "Countys" ("Id", "Name", "Initials") values (26, 'Pernambuco', 'PE');
Insert into "Countys" ("Id", "Name", "Initials") values (22, 'Piauí', 'PI');
Insert into "Countys" ("Id", "Name", "Initials") values (33, 'Rio de Janeiro', 'RJ');
Insert into "Countys" ("Id", "Name", "Initials") values (24, 'Rio Grande do Norte', 'RN');
Insert into "Countys" ("Id", "Name", "Initials") values (43, 'Rio Grande do Sul', 'RS');
Insert into "Countys" ("Id", "Name", "Initials") values (11, 'Rondônia', 'RO');
Insert into "Countys" ("Id", "Name", "Initials") values (14, 'Roraima', 'RR');
Insert into "Countys" ("Id", "Name", "Initials") values (42, 'Santa Catarina', 'SC');
Insert into "Countys" ("Id", "Name", "Initials") values (35, 'São Paulo', 'SP');
Insert into "Countys" ("Id", "Name", "Initials") values (28, 'Sergipe', 'SE');
Insert into "Countys" ("Id", "Name", "Initials") values (17, 'Tocantins', 'TO');
Insert into "Countys" ("Id", "Name", "Initials") values (99, 'Exterior', 'EX');